### ISSUE TITLE
callback function arguments are not set in the browser

### ISSUE THREAD

**Issue by andineck** [sindresorhus/each-async#6]
`each-async` does not work in chrome. The callback function arguments (item, index, done) are empty.

**Comment by andineck** [comment]
The problem does not come `each-async` itself, but from `set-immediate-shim`.
You can accept: https://github.com/sindresorhus/set-immediate-shim/pull/2
and update to the latest version.

**Comment by sindresorhus** [comment]
Should be fixed now. Thanks for the PR ;)
