### ISSUE TITLE
is necessary to ensure async iterator?

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/each-async#7]
I want to know, if using this package, need to be sure that the iterator function that you put in the method need to be [ensure async](https://github.com/caolan/async#ensureasyncfn).

I really don't know if this is a problem about how internally async works or if is a JS/Node  behaviour.

can you clarify this?

standalone async.ensureAsync => https://github.com/Kikobeats/ensure-async#ensure-async

**Comment by sindresorhus** [comment]
That's already handled for you: https://github.com/sindresorhus/each-async/blob/1c48306f44ccbacfc4c949d4e2f08f7a1505b1e9/index.js#L44

**Comment by Kikobeats** [comment]
sweet! :-)
