### ISSUE TITLE
Concurrency option

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/each-async#8]
Just the same, but in series.

What do you think to add an extra param to do this action? like:

```
js
const concurrency = 1;

eachAsync(['foo','bar','baz'], concurrency, (item, index, done) => {
    console.log(item, index);
    done();
}, error => {
    console.log('finished');
}
```

**Comment by shinnn** [comment]
You can use https://github.com/jb55/async-each-series instead.

**Comment by Kikobeats** [comment]
this library prevent call the callback more than one time. I like it!

**Comment by sindresorhus** [comment]
Yeah, sure, if someone does a PR. I'm all in on promises now, so I no longer use this. Should be an options object as the last argument, in case of future additional options.

**Comment by sindresorhus** [comment]
Closing as I've long ago have moved to promises and so should everyone else. See for what to do for concurrency control: https://github.com/sindresorhus/each-async/commit/05547b3d81e54de7bd705f87c94c4202d605c2c9
